FROM nvidia/cuda:11.6.0-base-ubuntu20.04
RUN apt update
RUN apt install -y pip python curl
RUN pip install torch==1.9.0
RUN pip install numpy>=1.18.2
RUN pip install tqdm
RUN apt install -y git
RUN git clone https://github.com/labdao/RefineGNN.git